/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  PublicApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { FlickrCustom } from "./client-custom";

export class Flickr extends FlickrCustom {
  readonly public: PublicApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.public = new PublicApi(configuration);
  }

}
