/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Album
 */
export interface Album {
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Album
     */
    'can_comment'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Album
     */
    'count_comments'?: number;
    /**
     * 
     * @type {number}
     * @memberof Album
     */
    'count_views'?: number;
    /**
     * 
     * @type {number}
     * @memberof Album
     */
    'date_create'?: number;
    /**
     * 
     * @type {number}
     * @memberof Album
     */
    'date_update'?: number;
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    'farm'?: string;
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof Album
     */
    'photos'?: number;
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    'primary'?: string;
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    'secret'?: string;
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    'server'?: string;
    /**
     * 
     * @type {number}
     * @memberof Album
     */
    'videos'?: number;
}

