/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ContextPhoto
 */
export interface ContextPhoto {
    /**
     * 
     * @type {string}
     * @memberof ContextPhoto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContextPhoto
     */
    'farm'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContextPhoto
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContextPhoto
     */
    'is_faved'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ContextPhoto
     */
    'license'?: number;
    /**
     * 
     * @type {string}
     * @memberof ContextPhoto
     */
    'media'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContextPhoto
     */
    'owner'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContextPhoto
     */
    'safe'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ContextPhoto
     */
    'secret'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContextPhoto
     */
    'server'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContextPhoto
     */
    'thumb'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContextPhoto
     */
    'url'?: string;
}

