/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Cover
 */
export interface Cover {
    /**
     * 
     * @type {string}
     * @memberof Cover
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Cover
     */
    'farm'?: string;
    /**
     * 
     * @type {string}
     * @memberof Cover
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Cover
     */
    'isfamily'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Cover
     */
    'isfriend'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Cover
     */
    'ispublic'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Cover
     */
    'owner'?: string;
    /**
     * 
     * @type {string}
     * @memberof Cover
     */
    'secret'?: string;
    /**
     * 
     * @type {string}
     * @memberof Cover
     */
    'server'?: string;
    /**
     * 
     * @type {string}
     * @memberof Cover
     */
    'y'?: string;
}

