/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Cover } from './cover';
import { GroupBlast } from './group-blast';
import { GroupDescription } from './group-description';
import { GroupRestrictions } from './group-restrictions';
import { GroupRoles } from './group-roles';
import { GroupThrottle } from './group-throttle';
import { PhotoURLs } from './photo-urls';

/**
 * 
 * @export
 * @interface Group
 */
export interface Group {
    /**
     * 
     * @type {GroupDescription}
     * @memberof Group
     */
    'description'?: GroupDescription;
    /**
     * 
     * @type {GroupBlast}
     * @memberof Group
     */
    'blast'?: GroupBlast;
    /**
     * 
     * @type {Cover}
     * @memberof Group
     */
    'cover'?: Cover;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    'coverphoto_farm'?: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    'coverphoto_server'?: string;
    /**
     * 
     * @type {PhotoURLs}
     * @memberof Group
     */
    'coverphoto_url'?: PhotoURLs;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    'iconfarm'?: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    'iconserver'?: string;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Group
     */
    'is_admin'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Group
     */
    'is_member'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Group
     */
    'is_moderator'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Group
     */
    'ispoolmoderated'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    'lang'?: string;
    /**
     * 
     * @type {GroupDescription}
     * @memberof Group
     */
    'members'?: GroupDescription;
    /**
     * 
     * @type {GroupDescription}
     * @memberof Group
     */
    'name'?: GroupDescription;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    'path_alias'?: string;
    /**
     * 
     * @type {GroupDescription}
     * @memberof Group
     */
    'pool_count'?: GroupDescription;
    /**
     * 
     * @type {number}
     * @memberof Group
     */
    'pool_rows'?: number;
    /**
     * 
     * @type {GroupDescription}
     * @memberof Group
     */
    'privacy'?: GroupDescription;
    /**
     * 
     * @type {GroupRestrictions}
     * @memberof Group
     */
    'restrictions'?: GroupRestrictions;
    /**
     * 
     * @type {GroupRoles}
     * @memberof Group
     */
    'roles'?: GroupRoles;
    /**
     * 
     * @type {GroupDescription}
     * @memberof Group
     */
    'rules'?: GroupDescription;
    /**
     * 
     * @type {GroupThrottle}
     * @memberof Group
     */
    'throttle'?: GroupThrottle;
    /**
     * 
     * @type {GroupDescription}
     * @memberof Group
     */
    'topic_count'?: GroupDescription;
}

