/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GroupRestrictions
 */
export interface GroupRestrictions {
    /**
     * 
     * @type {boolean}
     * @memberof GroupRestrictions
     */
    'art_ok'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GroupRestrictions
     */
    'has_geo'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GroupRestrictions
     */
    'images_ok'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GroupRestrictions
     */
    'moderate_ok'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GroupRestrictions
     */
    'photos_ok'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GroupRestrictions
     */
    'restricted_ok'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GroupRestrictions
     */
    'safe_ok'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GroupRestrictions
     */
    'screens_ok'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GroupRestrictions
     */
    'videos_ok'?: boolean;
}

