/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GroupDescription
 */
export interface GroupDescription {
    /**
     * 
     * @type {string}
     * @memberof GroupDescription
     */
    '_content'?: string;
}

