/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GroupThrottle
 */
export interface GroupThrottle {
    /**
     * 
     * @type {number}
     * @memberof GroupThrottle
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof GroupThrottle
     */
    'mode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupThrottle
     */
    'remaining'?: string;
}

