/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GroupBlast
 */
export interface GroupBlast {
    /**
     * 
     * @type {string}
     * @memberof GroupBlast
     */
    '_content'?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupBlast
     */
    'date_blast_added'?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupBlast
     */
    'user_id'?: string;
}

