/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Owner
 */
export interface Owner {
    /**
     * 
     * @type {string}
     * @memberof Owner
     */
    'iconfarm'?: string;
    /**
     * 
     * @type {string}
     * @memberof Owner
     */
    'iconserver'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Owner
     */
    'is_ad_free'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Owner
     */
    'ispro'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Owner
     */
    'location'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Owner
     */
    'noindexfollow'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Owner
     */
    'nsid'?: string;
    /**
     * 
     * @type {string}
     * @memberof Owner
     */
    'path_alias'?: string;
    /**
     * 
     * @type {string}
     * @memberof Owner
     */
    'realname'?: string;
    /**
     * 
     * @type {string}
     * @memberof Owner
     */
    'username'?: string;
}

