/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GroupDescription } from './group-description';

/**
 * 
 * @export
 * @interface PersonPhotos
 */
export interface PersonPhotos {
    /**
     * 
     * @type {GroupDescription}
     * @memberof PersonPhotos
     */
    'count'?: GroupDescription;
    /**
     * 
     * @type {GroupDescription}
     * @memberof PersonPhotos
     */
    'firstdate'?: GroupDescription;
    /**
     * 
     * @type {GroupDescription}
     * @memberof PersonPhotos
     */
    'firstdatetaken'?: GroupDescription;
    /**
     * 
     * @type {GroupDescription}
     * @memberof PersonPhotos
     */
    'views'?: GroupDescription;
}

