/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PhotoVisibility
 */
export interface PhotoVisibility {
    /**
     * 
     * @type {boolean}
     * @memberof PhotoVisibility
     */
    'isfamily'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PhotoVisibility
     */
    'isfriend'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PhotoVisibility
     */
    'ispublic'?: boolean;
}

