/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GroupDescription } from './group-description';
import { Owner } from './owner';
import { PhotoDates } from './photo-dates';
import { PhotoEditability } from './photo-editability';
import { PhotoNotes } from './photo-notes';
import { PhotoPeople } from './photo-people';
import { PhotoPermissions } from './photo-permissions';
import { PhotoTags } from './photo-tags';
import { PhotoUrls } from './photo-urls';
import { PhotoUsage } from './photo-usage';
import { PhotoVisibility } from './photo-visibility';

/**
 * 
 * @export
 * @interface Photo
 */
export interface Photo {
    /**
     * 
     * @type {PhotoTags}
     * @memberof Photo
     */
    'tags'?: PhotoTags;
    /**
     * 
     * @type {GroupDescription}
     * @memberof Photo
     */
    'title'?: GroupDescription;
    /**
     * 
     * @type {GroupDescription}
     * @memberof Photo
     */
    'description'?: GroupDescription;
    /**
     * 
     * @type {GroupDescription}
     * @memberof Photo
     */
    'comments'?: GroupDescription;
    /**
     * 
     * @type {PhotoDates}
     * @memberof Photo
     */
    'dates'?: PhotoDates;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    'dateuploaded'?: string;
    /**
     * 
     * @type {PhotoEditability}
     * @memberof Photo
     */
    'editability'?: PhotoEditability;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    'farm'?: string;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Photo
     */
    'isfavorite'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    'license'?: string;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    'media'?: string;
    /**
     * 
     * @type {PhotoNotes}
     * @memberof Photo
     */
    'notes'?: PhotoNotes;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    'originalsecret'?: string;
    /**
     * 
     * @type {Owner}
     * @memberof Photo
     */
    'owner'?: Owner;
    /**
     * 
     * @type {PhotoPeople}
     * @memberof Photo
     */
    'people'?: PhotoPeople;
    /**
     * 
     * @type {PhotoPermissions}
     * @memberof Photo
     */
    'permissions'?: PhotoPermissions;
    /**
     * 
     * @type {PhotoEditability}
     * @memberof Photo
     */
    'publiceditability'?: PhotoEditability;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    'rotation'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Photo
     */
    'safe'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    'safety_level'?: string;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    'secret'?: string;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    'server'?: string;
    /**
     * 
     * @type {PhotoUrls}
     * @memberof Photo
     */
    'urls'?: PhotoUrls;
    /**
     * 
     * @type {PhotoUsage}
     * @memberof Photo
     */
    'usage'?: PhotoUsage;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    'views'?: string;
    /**
     * 
     * @type {PhotoVisibility}
     * @memberof Photo
     */
    'visibility'?: PhotoVisibility;
}

