/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PhotoDates
 */
export interface PhotoDates {
    /**
     * 
     * @type {string}
     * @memberof PhotoDates
     */
    'lastupdate'?: string;
    /**
     * 
     * @type {string}
     * @memberof PhotoDates
     */
    'posted'?: string;
    /**
     * 
     * @type {string}
     * @memberof PhotoDates
     */
    'taken'?: string;
    /**
     * 
     * @type {string}
     * @memberof PhotoDates
     */
    'takengranularity'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PhotoDates
     */
    'takenunknown'?: boolean;
}

