/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PhotoUsage
 */
export interface PhotoUsage {
    /**
     * 
     * @type {boolean}
     * @memberof PhotoUsage
     */
    'canblog'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PhotoUsage
     */
    'candownload'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PhotoUsage
     */
    'canprint'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PhotoUsage
     */
    'canshare'?: boolean;
}

