/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PublicGetPhotoSizesResponseSizes } from './public-get-photo-sizes-response-sizes';

/**
 * 
 * @export
 * @interface PublicGetPhotoSizesResponse
 */
export interface PublicGetPhotoSizesResponse {
    /**
     * 
     * @type {PublicGetPhotoSizesResponseSizes}
     * @memberof PublicGetPhotoSizesResponse
     */
    'sizes'?: PublicGetPhotoSizesResponseSizes;
    /**
     * 
     * @type {string}
     * @memberof PublicGetPhotoSizesResponse
     */
    'stat'?: string;
}

