/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Photo } from './photo';

/**
 * 
 * @export
 * @interface PublicGetFavoritePhotosResponse
 */
export interface PublicGetFavoritePhotosResponse {
    /**
     * 
     * @type {number}
     * @memberof PublicGetFavoritePhotosResponse
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof PublicGetFavoritePhotosResponse
     */
    'pages'?: number;
    /**
     * 
     * @type {number}
     * @memberof PublicGetFavoritePhotosResponse
     */
    'perpage'?: number;
    /**
     * 
     * @type {Array<Photo>}
     * @memberof PublicGetFavoritePhotosResponse
     */
    'photos'?: Array<Photo>;
    /**
     * 
     * @type {number}
     * @memberof PublicGetFavoritePhotosResponse
     */
    'total'?: number;
}

