/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PublicGetPhotoLicensesResponseLicensesLicenseInner } from './public-get-photo-licenses-response-licenses-license-inner';

/**
 * 
 * @export
 * @interface PublicGetPhotoLicensesResponseLicenses
 */
export interface PublicGetPhotoLicensesResponseLicenses {
    /**
     * 
     * @type {Array<PublicGetPhotoLicensesResponseLicensesLicenseInner>}
     * @memberof PublicGetPhotoLicensesResponseLicenses
     */
    'license'?: Array<PublicGetPhotoLicensesResponseLicensesLicenseInner>;
}

