/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Group } from './group';

/**
 * 
 * @export
 * @interface PublicGetGroupInfoResponse
 */
export interface PublicGetGroupInfoResponse {
    /**
     * 
     * @type {Group}
     * @memberof PublicGetGroupInfoResponse
     */
    'group'?: Group;
    /**
     * 
     * @type {string}
     * @memberof PublicGetGroupInfoResponse
     */
    'stat'?: string;
}

