/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PublicUploadPhotoRequest
 */
export interface PublicUploadPhotoRequest {
    /**
     * 
     * @type {string}
     * @memberof PublicUploadPhotoRequest
     */
    'tags'?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicUploadPhotoRequest
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicUploadPhotoRequest
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicUploadPhotoRequest
     */
    'api_key': string;
    /**
     * 
     * @type {string}
     * @memberof PublicUploadPhotoRequest
     */
    'content_type'?: PublicUploadPhotoRequestContentTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PublicUploadPhotoRequest
     */
    'hidden'?: PublicUploadPhotoRequestHiddenEnum;
    /**
     * 
     * @type {string}
     * @memberof PublicUploadPhotoRequest
     */
    'is_family'?: PublicUploadPhotoRequestIsFamilyEnum;
    /**
     * 
     * @type {string}
     * @memberof PublicUploadPhotoRequest
     */
    'is_friend'?: PublicUploadPhotoRequestIsFriendEnum;
    /**
     * 
     * @type {string}
     * @memberof PublicUploadPhotoRequest
     */
    'is_public'?: PublicUploadPhotoRequestIsPublicEnum;
    /**
     * 
     * @type {Uint8Array | File | buffer.File}
     * @memberof PublicUploadPhotoRequest
     */
    'photo': Uint8Array | File | buffer.File;
    /**
     * 
     * @type {string}
     * @memberof PublicUploadPhotoRequest
     */
    'safety_level'?: PublicUploadPhotoRequestSafetyLevelEnum;
}

type PublicUploadPhotoRequestContentTypeEnum = '1' | '2' | '3'
type PublicUploadPhotoRequestHiddenEnum = '1' | '2'
type PublicUploadPhotoRequestIsFamilyEnum = '0' | '1'
type PublicUploadPhotoRequestIsFriendEnum = '0' | '1'
type PublicUploadPhotoRequestIsPublicEnum = '0' | '1'
type PublicUploadPhotoRequestSafetyLevelEnum = '1' | '2' | '3'


