/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PublicGetPhotoExifResponsePhotoExifInner } from './public-get-photo-exif-response-photo-exif-inner';

/**
 * 
 * @export
 * @interface PublicGetPhotoExifResponsePhoto
 */
export interface PublicGetPhotoExifResponsePhoto {
    /**
     * 
     * @type {string}
     * @memberof PublicGetPhotoExifResponsePhoto
     */
    'camera'?: string;
    /**
     * 
     * @type {Array<PublicGetPhotoExifResponsePhotoExifInner>}
     * @memberof PublicGetPhotoExifResponsePhoto
     */
    'exif'?: Array<PublicGetPhotoExifResponsePhotoExifInner>;
    /**
     * 
     * @type {string}
     * @memberof PublicGetPhotoExifResponsePhoto
     */
    'farm'?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicGetPhotoExifResponsePhoto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicGetPhotoExifResponsePhoto
     */
    'secret'?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicGetPhotoExifResponsePhoto
     */
    'server'?: string;
}

