/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PublicGetPhotoLicensesResponseLicensesLicenseInner
 */
export interface PublicGetPhotoLicensesResponseLicensesLicenseInner {
    /**
     * 
     * @type {number}
     * @memberof PublicGetPhotoLicensesResponseLicensesLicenseInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PublicGetPhotoLicensesResponseLicensesLicenseInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicGetPhotoLicensesResponseLicensesLicenseInner
     */
    'url'?: string;
}

