/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PublicGetPhotoExifResponsePhoto } from './public-get-photo-exif-response-photo';

/**
 * 
 * @export
 * @interface PublicGetPhotoExifResponse
 */
export interface PublicGetPhotoExifResponse {
    /**
     * 
     * @type {PublicGetPhotoExifResponsePhoto}
     * @memberof PublicGetPhotoExifResponse
     */
    'photo'?: PublicGetPhotoExifResponsePhoto;
    /**
     * 
     * @type {string}
     * @memberof PublicGetPhotoExifResponse
     */
    'stat'?: string;
}

