/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Topic } from './topic';

/**
 * 
 * @export
 * @interface PublicGetGroupDiscussionTopicsResponse
 */
export interface PublicGetGroupDiscussionTopicsResponse {
    /**
     * 
     * @type {number}
     * @memberof PublicGetGroupDiscussionTopicsResponse
     */
    'iconfarm'?: number;
    /**
     * 
     * @type {number}
     * @memberof PublicGetGroupDiscussionTopicsResponse
     */
    'iconserver'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PublicGetGroupDiscussionTopicsResponse
     */
    'ispoolmoderated'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PublicGetGroupDiscussionTopicsResponse
     */
    'lang'?: string;
    /**
     * 
     * @type {number}
     * @memberof PublicGetGroupDiscussionTopicsResponse
     */
    'members'?: number;
    /**
     * 
     * @type {string}
     * @memberof PublicGetGroupDiscussionTopicsResponse
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof PublicGetGroupDiscussionTopicsResponse
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof PublicGetGroupDiscussionTopicsResponse
     */
    'pages'?: number;
    /**
     * 
     * @type {number}
     * @memberof PublicGetGroupDiscussionTopicsResponse
     */
    'per_page'?: number;
    /**
     * 
     * @type {number}
     * @memberof PublicGetGroupDiscussionTopicsResponse
     */
    'privacy'?: number;
    /**
     * 
     * @type {Array<Topic>}
     * @memberof PublicGetGroupDiscussionTopicsResponse
     */
    'topics'?: Array<Topic>;
    /**
     * 
     * @type {number}
     * @memberof PublicGetGroupDiscussionTopicsResponse
     */
    'total'?: number;
}

