/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Album } from './album';

/**
 * 
 * @export
 * @interface PublicGetUserAlbumsResponse
 */
export interface PublicGetUserAlbumsResponse {
    /**
     * 
     * @type {number}
     * @memberof PublicGetUserAlbumsResponse
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof PublicGetUserAlbumsResponse
     */
    'pages'?: number;
    /**
     * 
     * @type {number}
     * @memberof PublicGetUserAlbumsResponse
     */
    'perpage'?: number;
    /**
     * 
     * @type {Array<Album>}
     * @memberof PublicGetUserAlbumsResponse
     */
    'photosets'?: Array<Album>;
    /**
     * 
     * @type {number}
     * @memberof PublicGetUserAlbumsResponse
     */
    'total'?: number;
}

