/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GroupDescription } from './group-description';

/**
 * 
 * @export
 * @interface PublicGetPhotoExifResponsePhotoExifInner
 */
export interface PublicGetPhotoExifResponsePhotoExifInner {
    /**
     * 
     * @type {string}
     * @memberof PublicGetPhotoExifResponsePhotoExifInner
     */
    'label'?: string;
    /**
     * 
     * @type {GroupDescription}
     * @memberof PublicGetPhotoExifResponsePhotoExifInner
     */
    'raw'?: GroupDescription;
    /**
     * 
     * @type {string}
     * @memberof PublicGetPhotoExifResponsePhotoExifInner
     */
    'tag'?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicGetPhotoExifResponsePhotoExifInner
     */
    'tagspace'?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicGetPhotoExifResponsePhotoExifInner
     */
    'tagspaceid'?: string;
}

