/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Size
 */
export interface Size {
    /**
     * 
     * @type {number}
     * @memberof Size
     */
    'height'?: number;
    /**
     * 
     * @type {string}
     * @memberof Size
     */
    'label'?: string;
    /**
     * 
     * @type {string}
     * @memberof Size
     */
    'media'?: string;
    /**
     * 
     * @type {string}
     * @memberof Size
     */
    'source'?: string;
    /**
     * 
     * @type {string}
     * @memberof Size
     */
    'url'?: string;
    /**
     * 
     * @type {number}
     * @memberof Size
     */
    'width'?: number;
}

