/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    '_content'?: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    'author'?: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    'authorname'?: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Tag
     */
    'machine_tag'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    'raw'?: string;
}

