/*
Flickr API Schema

A subset of Flickr's API defined in Swagger format.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GroupDescription } from './group-description';

/**
 * 
 * @export
 * @interface TopicReply
 */
export interface TopicReply {
    /**
     * 
     * @type {string}
     * @memberof TopicReply
     */
    'author'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TopicReply
     */
    'author_is_deleted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TopicReply
     */
    'author_path_alias'?: string;
    /**
     * 
     * @type {string}
     * @memberof TopicReply
     */
    'authorname'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TopicReply
     */
    'can_delete'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TopicReply
     */
    'can_edit'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TopicReply
     */
    'datecreate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TopicReply
     */
    'iconfarm'?: string;
    /**
     * 
     * @type {string}
     * @memberof TopicReply
     */
    'iconserver'?: string;
    /**
     * 
     * @type {string}
     * @memberof TopicReply
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TopicReply
     */
    'is_pro'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TopicReply
     */
    'lastedit'?: string;
    /**
     * 
     * @type {GroupDescription}
     * @memberof TopicReply
     */
    'message'?: GroupDescription;
}

